### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by placrosse** [lloeki/ex-mode#107]
[Enter steps to reproduce below:]

1. close last open file with :q  (no changes in file)
2. exception thrown
3. was using autohide-tree-view package 

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Users/placrosse/.atom/packages/ex-mode/lib/ex-state.coffee:59

TypeError: Cannot read property 'dispose' of undefined
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:28
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
  at disableAutohide (/Users/placrosse/.atom/packages/autohide-tree-view/lib/autohide-tree-view.js:72:15)
  at stop (/Users/placrosse/.atom/packages/autohide-tree-view/lib/main.js:117:43)
  at updateActivationState (/Users/placrosse/.atom/packages/autohide-tree-view/lib/main.js:92:45)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:284:27)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:410:17)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:466:16)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:443:12)
  at Ex.quit (/Users/placrosse/.atom/packages/ex-mode/lib/ex.coffee:75:36)
  at Ex.q (/Users/placrosse/.atom/packages/ex-mode/lib/ex.coffee:77:10)
  at /Users/placrosse/.atom/packages/ex-mode/lib/ex.coffee:1:1
  at Command.execute (/Users/placrosse/.atom/packages/ex-mode/lib/command.coffee:153:7)
  at ExState.processOpStack (/Users/placrosse/.atom/packages/ex-mode/lib/ex-state.coffee:53:17)
  at ExState.pushOperations (/Users/placrosse/.atom/packages/ex-mode/lib/ex-state.coffee:43:6)
  at ExViewModel.ViewModel.confirm (/Users/placrosse/.atom/packages/ex-mode/lib/view-model.coffee:13:14)
  at ExViewModel.module.exports.ExViewModel.confirm (/Users/placrosse/.atom/packages/ex-mode/lib/ex-view-model.coffee:35:5)
  at ExViewModel.confirm (/Users/placrosse/.atom/packages/ex-mode/lib/ex-view-model.coffee:1:1)
  at ex-command-mode-input.ExCommandModeInputElement.confirm (/Users/placrosse/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:46:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  7x -0:28.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:27.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 24x -0:27.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:14.7.0 tree-view:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:12.5.0 tree-view:toggle-focus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -0:11.1.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:09.9.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:07.9.0 vim-shift-movers:shift-text-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:06.8.0 vim-shift-movers:shift-text-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:05.9.0 vim-mode:undo (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.5.0 ex-mode:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:03.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 ex-mode:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.3.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-css",
      "autocomplete-atom-api",
      "autocomplete-html",
      "welcome",
      "update-package-dependencies",
      "spell-check",
      "package-generator",
      "metrics",
      "link",
      "language-yaml",
      "language-source",
      "language-shellscript",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-property-list",
      "autosave",
      "exception-reporting",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-css",
      "language-gfm",
      "language-go",
      "language-hyperlink",
      "language-java",
      "language-javascript",
      "language-less",
      "language-objective-c",
      "language-perl",
      "language-php"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autohide-tree-view, v0.25.1
clipboard-plus, v0.5.1
ex-mode, v0.7.0
language-rust, v0.4.5
linter, v1.9.1
linter-rust, v0.2.10
minimap, v4.15.0
minimap-git-diff, v4.1.8
racer, v0.17.2
relative-numbers, v0.2.4
remember-file-positions, v0.1.6
rust-api-docs-helper, v0.5.1
vim-mode, v0.62.0
vim-mode-clipboard-plus, v0.1.0
vim-shift-movers, v0.1.3
vim-surround, v0.8.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by FDiskas** [comment]
:white_large_square: https://github.com/jdc0589/jsformat-atom/issues/39
