### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pushSearchHistory' of undefined

### ISSUE THREAD

**Issue by dawsonbotsford** [lloeki/ex-mode#128]
1. edit javascript file
2. any global find and replace command `:%s/arguments/arg/g`

**Atom Version**: 1.5.0
**System**: Mac OS X 10.11.3
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'pushSearchHistory' of undefined

```
At /Users/dawsonbotsford/.atom/packages/ex-mode/lib/ex-state.coffee:59

TypeError: Cannot read property 'pushSearchHistory' of undefined
    at Ex.substitute (/Users/dawsonbotsford/.atom/packages/ex-mode/lib/ex.coffee:308:15)
    at Ex.s (/Users/dawsonbotsford/.atom/packages/ex-mode/lib/ex.coffee:331:17)
    at /Users/dawsonbotsford/.atom/packages/ex-mode/lib/ex.coffee:1:1
    at Command.execute (/Users/dawsonbotsford/.atom/packages/ex-mode/lib/command.coffee:153:7)
    at ExState.processOpStack (/Users/dawsonbotsford/.atom/packages/ex-mode/lib/ex-state.coffee:53:17)
    at ExState.pushOperations (/Users/dawsonbotsford/.atom/packages/ex-mode/lib/ex-state.coffee:43:6)
    at ExViewModel.ViewModel.confirm (/Users/dawsonbotsford/.atom/packages/ex-mode/lib/view-model.coffee:13:14)
    at ExViewModel.module.exports.ExViewModel.confirm (/Users/dawsonbotsford/.atom/packages/ex-mode/lib/ex-view-model.coffee:35:5)
    at ExViewModel.confirm (/Users/dawsonbotsford/.atom/packages/ex-mode/lib/ex-view-model.coffee:1:1)
    at ex-command-mode-input.ExCommandModeInputElement.confirm (/Users/dawsonbotsford/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:51:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  5x -1:59.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -1:37.4.0 ex-mode:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -1:37.4.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -1:37.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:37.2.0 blur (atom-text-editor.editor.mini.is-focused)
     -1:35.4.0 script:kill-process (div.panel.cli-status.panel-bottom)
  8x -1:33.4.0 blur (div.panel.cli-status.panel-bottom)
  2x -1:25 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:22.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:22.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:49.7.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:49.4.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:48.3.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:07.0 ex-mode:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:07.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:01.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-shortcuts, v0.0.2
ex-mode, v0.8.0
highlight-line, v0.11.1
linter, v1.11.3
linter-jsonlint, v1.1.5
linter-xo, v0.12.0
oceanic-next, v0.1.2
relative-numbers, v0.4.1
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
Looks like you don't have the vim-mode package installed. Since using ex-mode without vim-mode is unusual, substitute doesn't actually guard against it not being loaded.

Can you install vim-mode and see if the issue persists?

**Comment by dawsonbotsford** [comment]
I was using [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) with a custom keyboard binding to engage `ex-mode`. 

Switching back to `vim-mode` fixed it. Thanks!

**Comment by jazzpi** [comment]
Yes, vim-mode-plus doesn't really provide compatibility with vim-mode... Added this to #111.

Weird though that vim-mode-plus doesn't show up in your installed packages.
