### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by brucelandor** [lloeki/ex-mode#136]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /Users/blandor/.atom/packages/ex-mode/lib/ex-state.coffee:90

TypeError: Cannot read property 'then' of undefined
    at Formatter.module.exports.Formatter.formatEditor (/Users/blandor/.atom/packages/dart-tools/lib/formatter.coffee:66:19)
    at Formatter.formatEditor (/Users/blandor/.atom/packages/dart-tools/lib/formatter.coffee:1:1)
    at /Users/blandor/.atom/packages/dart-tools/lib/formatter.coffee:84:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1073:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:629:26)
    at /Users/blandor/.atom/packages/ex-mode/lib/ex.coffee:208:27
    at trySave (/Users/blandor/.atom/packages/ex-mode/lib/ex.coffee:11:5)
    at Ex.write (/Users/blandor/.atom/packages/ex-mode/lib/ex.coffee:208:9)
    at Ex.w (/Users/blandor/.atom/packages/ex-mode/lib/ex.coffee:228:6)
    at /Users/blandor/.atom/packages/ex-mode/lib/ex.coffee:1:1
    at Command.execute (/Users/blandor/.atom/packages/ex-mode/lib/command.coffee:153:7)
    at ExState.processOpStack (/Users/blandor/.atom/packages/ex-mode/lib/ex-state.coffee:83:19)
    at ExState.pushOperations (/Users/blandor/.atom/packages/ex-mode/lib/ex-state.coffee:69:21)
    at ExViewModel.ViewModel.confirm (/Users/blandor/.atom/packages/ex-mode/lib/view-model.coffee:25:20)
    at ExViewModel.module.exports.ExViewModel.confirm (/Users/blandor/.atom/packages/ex-mode/lib/ex-view-model.coffee:53:44)
    at ExViewModel.confirm (/Users/blandor/.atom/packages/ex-mode/lib/ex-view-model.coffee:3:61)
    at ex-command-mode-input.ExCommandModeInputElement.confirm (/Users/blandor/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:51:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:21 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:20.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:15.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:15.3.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:14.5.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:14.3.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:14 dartlang:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:14 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.2.0 dartlang:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.2.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:06.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:03.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.6.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.2.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.5.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-playground"
    ],
    "followSymlinks": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.6
autocomplete-go, v1.0.5
builder-go, v1.0.0
dart-tools, v0.9.23
dartlang, v0.6.9
environment, v1.2.0
ex-mode, v0.8.0
file-icons, v1.7.0
go-config, v1.1.2
go-find-references, v1.2.3
go-get, v1.0.2
go-plus, v4.1.0
gofmt, v1.1.3
gometalinter-linter, v1.1.0
gorename, v1.0.0
language-go, v0.42.0
language-rust, v0.4.6
linter, v1.11.4
linter-dartanalyzer, v0.3.2
linter-rust, v0.4.1
linter-swiftc, v2.0.0
navigator-godef, v1.0.2
python-indent, v0.4.3
python-tools, v0.6.7
synced-sidebar, v0.4.3
tester-go, v1.0.3
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
How did you  encounter this error? And does it also occur when you disable the `dart-tools` package?

**Comment by brucelandor** [comment]
It happened when I was saving a .dart file use :w. And it still happened after i disabled dart-tools.

**Comment by hultberg** [comment]
@brucelandor Can you reproduce this on atom 1.18?
