### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by dlants** [lloeki/ex-mode#149]
[Enter steps to reproduce below:]
1. open file
2. split with `:vs`
3. switch to right pane (ctrl-l binding)
4. quite with `:wq`
5. do 1-4 quickly a few times.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.10.0
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Users/dlants/.atom/packages/ex-mode/lib/ex-state.coffee:59

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:73:26)
    at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1544:35)
    at Object.format (/Users/dlants/.atom/packages/elm-format/lib/elm-format.js:99:33)
    at /Users/dlants/.atom/packages/elm-format/lib/elm-format.js:49:25
    at Object.debounce (/Users/dlants/.atom/packages/elm-format/lib/elm-format.js:57:7)
    at /Users/dlants/.atom/packages/elm-format/lib/elm-format.js:48:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at /Users/dlants/.atom/packages/ex-mode/lib/ex.coffee:208:27
    at trySave (/Users/dlants/.atom/packages/ex-mode/lib/ex.coffee:11:5)
    at Ex.write (/Users/dlants/.atom/packages/ex-mode/lib/ex.coffee:208:9)
    at Ex.wq (/Users/dlants/.atom/packages/ex-mode/lib/ex.coffee:231:6)
    at /Users/dlants/.atom/packages/ex-mode/lib/ex.coffee:1:1
    at Command.execute (/Users/dlants/.atom/packages/ex-mode/lib/command.coffee:153:7)
    at ExState.processOpStack (/Users/dlants/.atom/packages/ex-mode/lib/ex-state.coffee:53:17)
    at ExState.pushOperations (/Users/dlants/.atom/packages/ex-mode/lib/ex-state.coffee:43:6)
    at ExViewModel.ViewModel.confirm (/Users/dlants/.atom/packages/ex-mode/lib/view-model.coffee:13:14)
    at ExViewModel.module.exports.ExViewModel.confirm (/Users/dlants/.atom/packages/ex-mode/lib/ex-view-model.coffee:35:5)
    at ExViewModel.confirm (/Users/dlants/.atom/packages/ex-mode/lib/ex-view-model.coffee:1:1)
    at ex-command-mode-input.ExCommandModeInputElement.confirm (/Users/dlants/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:51:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:03.4.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode)
  5x -0:03.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:02.0 ex-mode:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:02.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode)
  4x -0:01.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 window:focus-pane-on-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.4.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.4.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode)
     -0:01.4.0 blur (atom-pane.pane.active)
     -0:01.0 ex-mode:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.9.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
elm-format, v1.2.1
ex-mode, v0.10.0
language-elm, v1.5.0
linter, v1.11.14
linter-elm-make, v0.9.2
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by hultberg** [comment]
Can't reproduce this on atom 1.18.
