### ISSUE TITLE
Uncaught Error: spawnSync /bin/sh ENOENT

### ISSUE THREAD

**Issue by DamienGong** [lloeki/ex-mode#175]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.1
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package 0.13.1

### Stack Trace

Uncaught Error: spawnSync /bin/sh ENOENT

```
At /home/dag/.atom/packages/ex-mode/lib/ex-state.coffee:59

Error: spawnSync /bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at spawnSync (child_process.js:473:20)
    at execSync (child_process.js:529:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:680:22)
    at ClangFormat.module.exports.ClangFormat.format (/packages/clang-format/lib/clang-format.coffee:75:16)
    at /packages/clang-format/lib/clang-format.coffee:28:29
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:819:18)
    at /packages/clang-format/lib/clang-format.coffee:28:16
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1060:20)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:890:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveItems (/app.asar/src/pane.js:800:16)
    at PaneContainer.module.exports.PaneContainer.saveAll (/app.asar/src/pane-container.js:224:14)
    at Workspace.module.exports.Workspace.saveAll (/app.asar/src/workspace.js:685:33)
    at Ex.wall (/packages/ex-mode/lib/ex.coffee:239:20)
    at Ex.wa (/packages/ex-mode/lib/ex.coffee:248:6)
    at /packages/ex-mode/lib/ex.coffee:1:1
    at Command.execute (/packages/ex-mode/lib/command.coffee:191:9)
    at ExState.processOpStack (/packages/ex-mode/lib/ex-state.coffee:53:17)
    at ExState.pushOperations (/packages/ex-mode/lib/ex-state.coffee:43:6)
    at ExViewModel.ViewModel.confirm (/packages/ex-mode/lib/view-model.coffee:13:14)
    at ExViewModel.module.exports.ExViewModel.confirm (/packages/ex-mode/lib/ex-view-model.coffee:56:5)
    at ExViewModel.confirm (/packages/ex-mode/lib/ex-view-model.coffee:1:1)
    at /packages/ex-mode/lib/ex-normal-mode-input-element.coffee:51:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
 95x -6:13.7.0 vim-mode:move-up (input.hidden-input)
     -6:03.0 vim-mode:move-down (input.hidden-input)
  8x -6:02.3.0 vim-mode:move-up (input.hidden-input)
 10x -6:01.1.0 vim-mode:move-down (input.hidden-input)
     -0:34.6.0 vim-mode:activate-insert-mode (input.hidden-input)
     -0:29.5.0 core:move-left (input.hidden-input)
  3x -0:28.3.0 core:backspace (input.hidden-input)
     -0:18.3.0 core:move-right (input.hidden-input)
  5x -0:18 editor:newline (input.hidden-input)
  2x -0:08.8.0 core:backspace (input.hidden-input)
     -0:08.1.0 vim-mode:activate-normal-mode (input.hidden-input)
  3x -0:07.9.0 vim-mode:reset-normal-mode (input.hidden-input)
     -0:07.2.0 ex-mode:open (input.hidden-input)
     -0:06.3.0 core:confirm (input.hidden-input)
  3x -0:00.2.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.3 
autocomplete-clang 0.10.0 
busy 0.7.0 
clang-format 1.27.0 
ex-mode 0.13.1 
platformio-ide-terminal 2.2.2 
project-manager 3.3.3 
remote-atom 1.3.10 
vim-mode 0.66.0 
```

**Comment by hultberg** [comment]
@DamienGong Is this still occurring on current atom stable (1.18)?
