### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by k** [lloeki/ex-mode#203]
[Enter steps to reproduce:]

1. Open file
2. Prettier-format
3. Start enjoying errors

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package 0.18.0

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:95

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:95:11)
    at executeDispatchesAndRelease (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:41:28)
    at executeDispatchesAndReleaseTopLevel (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:52:16)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/forEachAccumulated.js:22:15)
    at Object.processEventQueue (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:252:13)
    at runEventQueueInBatch (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:15:24)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:25:11)
    at handleTopLevelImpl (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:70:30)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:32)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:95:33)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:145:26)
    at HTMLElement.PaneElement.activated (/app.asar/src/pane-element.js:117:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1003:24)
    at HTMLDivElement.ExCommandModeInputElement.removePanel (/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:64:36)
    at HTMLDivElement.ExCommandModeInputElement.cancel (/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:61:6)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
```

### Commands

```
     -0:36.3.0 fuzzy-finder:toggle-file-finder (atom-pane.pane)
     -0:31.9.0 core:move-down (input.hidden-input)
     -0:29.9.0 core:confirm (input.hidden-input)
 19x -0:28.6.0 vim-mode-plus:move-down (input.hidden-input)
  2x -0:27.4.0 vim-mode-plus:scroll-half-screen-down (input.hidden-input)
  2x -0:26.8.0 vim-mode-plus:move-up (input.hidden-input)
     -0:26 prettier:format (input.hidden-input)
     -0:24.6.0 datatip:toggle (input.hidden-input)
     -0:24.6.0 vim-mode-plus:move-up (input.hidden-input)
     -0:24.6.0 vim-mode-plus:move-down (input.hidden-input)
     -0:23.6.0 vim-mode-plus:move-up (input.hidden-input)
  3x -0:23.3.0 vim-mode-plus:move-down (input.hidden-input)
     -0:22.1.0 ex-mode:open (input.hidden-input)
  3x -0:17.3.0 blur (input.hidden-input)
     -0:15.3.0 settings-view:open (input.hidden-input)
 17x -0:15.2.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-easy-jsdoc 4.12.4 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
ex-mode 0.18.0 
graphql-autocomplete 1.1.1 
intentions 1.1.5 
language-babel 2.80.2 
language-graphql 0.9.0 
language-javascript-jsx 0.3.7 
language-markdown 0.25.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-stylelint 4.1.0 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
nuclide 0.270.0 
prettier-atom 0.41.0 
vim-mode-plus 1.22.0 
```

**Comment by hultberg** [comment]
I'm unable to reproduce this issue. I searched in atom/atom issues and noticed this has been reported with the exact same stacktrace several times. See atom/atom#15093

Can you try to disable ex-mode and see if you encounter the same bug doing the same you did before? Thanks.

**Comment by k** [comment]
Yeah I did :( Seems like to be a bug with atom. Maybe prettier?
