### ISSUE TITLE
Uncaught TypeError: selection.isEmpty is not a function

### ISSUE THREAD

**Issue by dpendolino** [lloeki/ex-mode#205]
[Enter steps to reproduce:]

1. Attempt to enter ex-mode:open

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: "Arch Linux"
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package 0.18.0

### Stack Trace

Uncaught TypeError: selection.isEmpty is not a function

```
At /home/dpendolino/.atom/packages/ex-mode/lib/ex-state.coffee:67

TypeError: selection.isEmpty is not a function
    at ExState.getSelections (/packages/ex-mode/lib/ex-state.coffee:67:24)
    at /packages/ex-mode/lib/command.coffee:8:28)
    at ExState.registerOperationCommands.open (/packages/ex-mode/lib/ex-state.coffee:15:24)
    at HTMLElement.pushFn (/packages/ex-mode/lib/ex-state.coffee:29:41)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:388:30)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:108:34)
```

### Commands

```
  4x -2:15.4.0 core:backspace (input.hidden-input)
  5x -2:14.4.0 core:move-right (input.hidden-input)
     -2:12.3.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -2:11.8.0 ex-mode:open (input.hidden-input)
     -2:11.7.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -2:11.5.0 vim-mode-plus:move-to-first-character-of-line-down (input.hidden-input)
  2x -2:09.3.0 blur (input.hidden-input)
     -2:08.6.0 intentions:highlight (input.hidden-input)
     -2:08.4.0 core:save (input.hidden-input)
  5x -2:06.3.0 blur (input.hidden-input)
     -2:06.3.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-clear-night-syntax.theme-clear-night-ui)
 12x -2:03.7.0 blur (input.hidden-input)
     -1:52.6.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -1:52.2.0 intentions:highlight (input.hidden-input)
     -1:51.9.0 core:save (input.hidden-input)
 14x -1:50.9.0 blur (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
ansible-snippets 0.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.9 
atom-ctags 5.1.2 
atom-jade 0.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.1 
atom-meld 0.3.5 
autocomplete-ansible 0.1.15 
autocomplete-asciidoc 0.1.2 
autocomplete-awk 0.1.2 
autocomplete-bash-builtins 0.3.5 
autocomplete-ctags 0.4.1 
autocomplete-date 0.4.0 
autocomplete-js-import 1.4.0 
autocomplete-json 5.5.2 
autocomplete-modules 1.8.0 
autocomplete-php 0.3.7 
autocomplete-python 1.10.5 
autocomplete-xml 0.9.4 
busy-signal 1.4.3 
clear-night-syntax 1.3.16 
clear-night-ui 1.3.9 
clipboard-plus 0.5.1 
docblockr 0.13.5 
editorconfig 2.2.2 
ex-mode 0.18.0 
file-type-icons 1.3.4 
git-control 0.9.0 
git-plus 7.10.0 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-ansible 0.2.1 
language-docker 1.1.8 
language-markdown 0.25.1 
language-powershell 4.0.0 
linter 2.2.0 
linter-ansible-linting 1.3.1 
linter-docker 0.3.0 
linter-eslint 8.4.0 
linter-flake8 2.3.0 
linter-js-standard 4.2.0 
linter-js-yaml 1.2.8 
linter-jsonlint 1.3.0 
linter-php 1.5.1 
linter-shellcheck 1.4.6 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.3 
minimap 4.29.7 
minimap-pigments 0.2.2 
persistent-undo 1.3.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
pretty-json 1.6.4 
project-manager 3.3.5 
python-autopep8 0.1.4 
sort-lines 0.18.0 
split-diff 1.5.2 
symbols-tree-view 0.14.0 
sync-settings 0.8.3 
tree-view-git-status 1.4.0 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 1.25.1 
```

**Comment by donutcho** [comment]
A workaround for my case, disabling package [elm-navigator](https://atom.io/packages/elm-navigator) is works. (some conflicts occur?)

**Comment by ccapndave** [comment]
I also have this problem, but I need `elm-navigator` and can't disable it!

**Comment by tay3223** [comment]
我也遇到了同样的问题，请问该怎么解决？
