### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ahmadseleem** [lloeki/ex-mode#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/ahmad/.atom/packages/ex-mode/lib/ex-state.coffee:46

TypeError: Cannot read property 'length' of undefined
  at ExState.processOpStack (/Users/ahmad/.atom/packages/ex-mode/lib/ex-state.coffee:46:24)
  at ExState.pushOperations (/Users/ahmad/.atom/packages/ex-mode/lib/ex-state.coffee:39:6)
  at atom-text-editor.pushFn (/Users/ahmad/.atom/packages/ex-mode/lib/ex-state.coffee:28:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:28.5 core:backspace (atom-text-editor.editor.vim-mode.command-mode)
     -0:27.2 tree-view:toggle-focus (atom-text-editor.editor.vim-mode.command-mode)
     -0:26.3 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:25.6 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:22.5 tree-view:toggle-focus (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:21.8 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.5 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 16x -0:19.5 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
     -0:17.3 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.command-mode)
     -0:08.4 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:07.8 vim-mode:move-right (atom-text-editor.editor.vim-mode.command-mode)
     -0:07.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.command-mode)
     -0:05.3 core:backspace (atom-text-editor.editor.vim-mode.command-mode)
     -0:04.5 editor:newline (atom-text-editor.editor.vim-mode.command-mode)
     -0:02.7 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:02.2 ex-mode:open (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "toggle-tabs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.11.0
ex-mode, v0.3.1
language-haml, v0.15.0
language-scheme, v1.3.0
language-swift, v0.3.0
vim-mode, v0.39.0

# Dev
No dev packages
```

**Comment by ahmadseleem** [comment]
It seems to be working fine now after restating atom.

**Comment by lloeki** [comment]
Probably some stale state being reached too late after the update. Chime in if it comes up again.

**Comment by lloeki** [comment]
FYI, I just got it once too, but could not reproduce it again.

**Comment by ahmadseleem** [comment]
As you said, I think that was the case...

**Comment by jazzpi** [comment]
I think I found out what produces this.

If you press `:` to open the input view and then click back in the editor, the view isn't closed. So if you press `.` again, you have two input views. Then you get the error.

**Comment by jazzpi** [comment]
This should probably be reopened.

**Comment by lloeki** [comment]
You're right.

**Comment by francisbrito** [comment]
Got this error while writing ES6 code.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Ubuntu 14.04.3
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.7.0


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/francis/.atom/packages/ex-mode/lib/ex-state.coffee:7

TypeError: Cannot read property 'length' of undefined
  at ExState.processOpStack (/home/francis/.atom/packages/ex-mode/lib/ex-state.coffee:7:3)
  at ExState.pushOperations (/home/francis/.atom/packages/ex-mode/lib/ex-state.coffee:7:3)
  at atom-text-editor.pushFn (/home/francis/.atom/packages/ex-mode/lib/ex-state.coffee:29:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -6:12 find-and-replace:find-next (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:09.7.0 core:delete (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:04.6.0 vim-mode:delete (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.8.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:03.8.0 blur (atom-text-editor.editor.mini)
     -0:03.7.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:03.6.0 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  5x -0:03.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:02.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:01.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:01.6.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:01.2.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:01.2.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.8.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.8.0 vim-mode:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:00.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/francis/Workspace",
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "ternjs",
      "autocomplete-clang",
      "autocomplete-emojis",
      "atom-terminal-panel",
      "turbo-javascript",
      "advanced-open-file",
      "autocomplete-ruby",
      "rspec-snippets",
      "sort-lines",
      "term2"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-ternjs, v0.7.2
autocomplete-sass, v0.1.0
docblockr, v0.7.3
editorconfig, v1.2.0
emmet, v2.3.12
ex-mode, v0.7.0
language-babel, v0.14.0
language-docker, v1.1.3
language-gherkin, v1.0.2
language-gitignore, v0.2.0
language-haml, v0.21.0
language-jade, v0.6.2
language-javascript-better, v1.5.0
linter, v1.5.1
linter-eslint, v3.0.2
minimap, v4.13.3
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by justinnoah** [comment]
I also received this error, happened immediately after updating ex-mode. Restarted Atom and the issue went away. I do not recall which version of ex-mode I had to begin with, but I did update to 0.8.0

**Comment by KurtRMueller** [comment]
This just happened to me as well. Restarting Atom after updating `ex-mode` seems to do the trick.

**Comment by wakeless** [comment]
I'm having this issue while hitting `:w` with latest version of ex-mode and `1.19.0-beta1`

```TypeError: Cannot read property 'length' of undefined
    at Command.execute (/Users/mgall/.atom/packages/ex-mode/lib/command.coffee:76:41)
    at ExState.processOpStack (/Users/mgall/.atom/packages/ex-mode/lib/ex-state.coffee:53:17)
    at ExState.pushOperations (/Users/mgall/.atom/packages/ex-mode/lib/ex-state.coffee:43:6)
    at ExViewModel.ViewModel.confirm (/Users/mgall/.atom/packages/ex-mode/lib/view-model.coffee:13:14)
    at ExViewModel.module.exports.ExViewModel.confirm (/Users/mgall/.atom/packages/ex-mode/lib/ex-view-model.coffee:56:5)
    at ExViewModel.confirm (/Users/mgall/.atom/packages/ex-mode/lib/ex-view-model.coffee:1:1)
    at HTMLDivElement.ExCommandModeInputElement.confirm (/Users/mgall/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:51:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:65)```

**Comment by sophaskins** [comment]
Also seeing it in using ex mode to switch lines, ie `:5`
Also on 1.19.0-beta1

similar/same stacktrace:
```
TypeError: Cannot read property 'length' of undefined
    at Command.execute (/Users/sophaskins/.atom/packages/ex-mode/lib/command.coffee:76:41)
    at ExState.processOpStack (/Users/sophaskins/.atom/packages/ex-mode/lib/ex-state.coffee:53:17)
    at ExState.pushOperations (/Users/sophaskins/.atom/packages/ex-mode/lib/ex-state.coffee:43:6)
    at ExViewModel.ViewModel.confirm (/Users/sophaskins/.atom/packages/ex-mode/lib/view-model.coffee:13:14)
    at ExViewModel.module.exports.ExViewModel.confirm (/Users/sophaskins/.atom/packages/ex-mode/lib/ex-view-model.coffee:56:5)
    at ExViewModel.confirm (/Users/sophaskins/.atom/packages/ex-mode/lib/ex-view-model.coffee:1:1)
    at HTMLDivElement.ExCommandModeInputElement.confirm (/Users/sophaskins/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:51:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

**Comment by sophaskins** [comment]
The error line in question (https://github.com/lloeki/ex-mode/blob/545f13294e925d5e7b2407aa70f41390eee1c666/lib/command.coffee#L76) suggests that maybe this has to do with the [new buffer API](https://github.com/atom/superstring) in 1.19? https://github.com/atom/atom/releases/tag/v1.19.0-beta0

**Comment by bronson** [comment]
@sophaskins's PR fixes this issue: https://github.com/lloeki/ex-mode/pull/184

You need to apply that change if you want to use ex-mode on 1.19 (and, with the speed improvements, you do!)
