### ISSUE TITLE
Length error

### ISSUE THREAD

**Issue by romgrk** [lloeki/ex-mode#43]
The following error arise, usually on the second time I press ':'.

/home/romgrk/.atom/packages/ex-mode/lib/ex-state.coffee:47

TypeError: Cannot read property 'length' of undefined
  at ExState.processOpStack (/home/romgrk/.atom/packages/ex-mode/lib/ex-state.coffee:47:24)
  at ExState.pushOperations (/home/romgrk/.atom/packages/ex-mode/lib/ex-state.coffee:40:6)
  at atom-text-editor.pushFn (/home/romgrk/.atom/packages/ex-mode/lib/ex-state.coffee:29:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at KeymapManager.module.exports.KeymapManager.terminatePendingState (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:502:14)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:392:21)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

**Comment by lloeki** [comment]
I am currently investigating this. Something is off in the stack processing.

**Comment by lloeki** [comment]
fixed by c43b2658
