### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

### ISSUE THREAD

**Issue by KodaiNakamura** [lloeki/ex-mode#58]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:207

TypeError: Cannot read property 'hiddenInputComponent' of null
  at atom-text-editor.TextEditorElement.blurred (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:207:51)
  at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:182:26)
  at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:125:19)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:615:27)
  at ex-command-mode-input.ExCommandModeInputElement.removePanel (/Users/K-Nakamura/.atom/packages/ex-mode/lib/ex-command-mode-input-element.coffee:57:36)
  at ex-command-mode-input.ExCommandModeInputElement.confirm (/Users/K-Nakamura/.atom/packages/ex-mode/lib/ex-command-mode-input-element.coffee:47:6)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:02.7.0 ex-mode:open (input.hidden-input)
     -0:02.5.0 core:confirm (input.hidden-input)
  3x -0:02.5.0 blur (input.hidden-input)
     -0:00.4.0 ex-mode:open (input.hidden-input)
  3x -0:00.4.0 blur (input.hidden-input)
     -0:00.2.0 core:confirm (input.hidden-input)
  3x -0:00.2.0 blur (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-python",
      "minimap",
      "autocomplete-plus-python-jedi",
      "linter-python-pep8",
      "linter-pep8",
      "term2"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-runner, v2.4.1
autocomplete-paths, v1.0.2
docblockr, v0.7.2
emmet, v2.3.10
ex-mode, v0.5.1
file-icons, v1.5.7
highlight-column, v0.4.3
japanese-wrap, v0.2.10
language-rdf, v0.2.0
linter, v0.12.7
linter-javac, v0.1.4
linter-pylint, v0.2.2
project-manager, v1.15.10
vim-mode, v0.53.0
vim-mode-visual-block, v0.2.4
vim-surround, v0.7.0

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
I assume you get this error when you save (see #56). If that is the case, I can't reproduce it like that - could you try disabling all community packages but `vim-mode` and `ex-mode` and see if it works then? If it does work, please try reenabling one package at a time to see which package conflicts.

**Comment by ELD** [comment]
Hey there, I get the same issue on save.

I went ahead and disabled all community packages like you said in your above comment, @jazzpi, but even after doing that, I still get the error. I only have `vim-mode` and `ex-mode` 

Here's the full error report:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.5
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.5.1


### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:218

TypeError: Cannot read property 'hiddenInputComponent' of null
    at atom-text-editor.TextEditorElement.blurred (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:218:51)
    at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:193:26)
    at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:125:19)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:627:27)
    at ex-command-mode-input.ExCommandModeInputElement.removePanel (/Users/eric/.atom/packages/ex-mode/lib/ex-command-mode-input-element.coffee:81:38)
    at ex-command-mode-input.ExCommandModeInputElement.confirm (/Users/eric/.atom/packages/ex-mode/lib/ex-command-mode-input-element.coffee:68:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
```

### Commands

```
     -1:32.9.0 settings-view:open (input.hidden-input)
  6x -1:32.8.0 blur (input.hidden-input)
     -0:37.3.0 core:close (div.settings-view.pane-item)
  2x -0:37.3.0 blur (div.settings-view.pane-item)
     -0:36.8.0 core:close (input.hidden-input)
  5x -0:36.8.0 blur (input.hidden-input)
     -0:34.9.0 ex-mode:open (input.hidden-input)
  3x -0:34.9.0 blur (input.hidden-input)
     -0:34.6.0 core:confirm (input.hidden-input)
  8x -0:34.6.0 blur (input.hidden-input)
     -0:32 settings-view:open (input.hidden-input)
  9x -0:31.9.0 blur (input.hidden-input)
     -0:00.9.0 ex-mode:open (input.hidden-input)
  3x -0:00.9.0 blur (input.hidden-input)
     -0:00.7.0 core:confirm (input.hidden-input)
  3x -0:00.6.0 blur (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "highlight-line",
      "haskell-ghc-mod",
      "ide-haskell",
      "autocomplete-haskell",
      "autocomplete-php",
      "advanced-new-file",
      "autocomplete-modules",
      "autocomplete-paths",
      "easy-motion-redux",
      "file-icons",
      "language-haskell",
      "project-manager",
      "vim-mode-visual-block",
      "vim-surround"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.4
ex-mode, v0.5.1
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by lloeki** [comment]
@ELD is this still a problem?

**Comment by ELD** [comment]
@lloeki Not at the moment. I'm not sure what causes it, but I blew away my `.atom` folder awhile back and reinstalling fixed the issue. I'm not sure what causes it to pop up, but it just will randomly start throwing that error for no apparent reason. I'll try to pay closer attention to what I did before it pops up, if it resurfaces.

**Comment by elvis-bi** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.7.0


### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:219

TypeError: Cannot read property 'hiddenInputComponent' of null
  at atom-text-editor.TextEditorElement.blurred (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:219:51)
  at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:194:26)
  at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:125:19)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:631:27)
  at ex-command-mode-input.ExCommandModeInputElement.removePanel (/Users/macbookair/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:57:36)
  at ex-command-mode-input.ExCommandModeInputElement.confirm (/Users/macbookair/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:47:6)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -2:29.7.0 vim-mode:move-to-next-word (input.hidden-input)
  2x -2:29 vim-mode:move-down (input.hidden-input)
     -2:28.5.0 vim-mode:reset-normal-mode (input.hidden-input)
  2x -2:26.9.0 vim-mode:move-up (input.hidden-input)
  2x -2:26.5.0 vim-mode:move-down (input.hidden-input)
     -2:25.7.0 vim-mode:move-to-next-word (input.hidden-input)
     -2:25 vim-mode:reset-normal-mode (input.hidden-input)
  2x -2:24.7.0 vim-mode:move-up (input.hidden-input)
  2x -2:24.3.0 vim-mode:move-down (input.hidden-input)
 25x -2:22.3.0 blur (input.hidden-input)
  2x -0:03.5.0 vim-mode:reset-normal-mode (input.hidden-input)
  3x -0:02.6.0 vim-mode:move-down (input.hidden-input)
     -0:01.9.0 ex-mode:open (input.hidden-input)
  3x -0:01.9.0 blur (input.hidden-input)
     -0:01.6.0 core:confirm (input.hidden-input)
  3x -0:01.6.0 blur (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
docblockr, v0.7.3
docs-snippets, v0.8.0
ex-mode, v0.7.0
project-manager, v1.15.11
terminal-panel, v1.14.1
vim-mode, v0.58.0
vim-mode-visual-block, v0.2.13

# Dev
No dev packages
```

**Comment by gistart** [comment]
According to stacktrace, the problem is with "hidden input", which is a command line, appearing after ":" command.

Error occurs every time command line is closed, no matter was a command given, or it was just closed with esc.

**Atom Version**: 1.0.11
**System**: Ubuntu 15.04
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.7.0


### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /opt/atom/resources/app.asar/src/text-editor-element.js:219

TypeError: Cannot read property 'hiddenInputComponent' of null
  at atom-text-editor.TextEditorElement.blurred (/opt/atom/resources/app.asar/src/text-editor-element.js:219:51)
  at HTMLInputElement.<anonymous> (/opt/atom/resources/app.asar/src/text-editor-element.js:194:26)
  at atom-pane.PaneElement.activated (/opt/atom/resources/app.asar/src/pane-element.js:125:19)
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.activate (/opt/atom/resources/app.asar/src/pane.js:639:27)
  at ex-command-mode-input.ExCommandModeInputElement.removePanel (/home/gistart/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:57:36)
  at ex-command-mode-input.ExCommandModeInputElement.confirm (/home/gistart/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:47:6)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:245:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:41.9.0 ex-mode:open (input.hidden-input)
  3x -0:41.9.0 blur (input.hidden-input)
     -0:41.6.0 core:confirm (input.hidden-input)
 22x -0:41.6.0 blur (input.hidden-input)
     -0:32.2.0 ex-mode:open (input.hidden-input)
  3x -0:32.2.0 blur (input.hidden-input)
     -0:32 core:confirm (input.hidden-input)
 22x -0:32 blur (input.hidden-input)
     -0:23.9.0 ex-mode:open (input.hidden-input)
  3x -0:23.9.0 blur (input.hidden-input)
     -0:23.6.0 core:confirm (input.hidden-input)
 17x -0:23.6.0 blur (input.hidden-input)
     -0:01.0 ex-mode:open (input.hidden-input)
  3x -0:01.0 blur (input.hidden-input)
     -0:00.7.0 core:confirm (input.hidden-input)
  3x -0:00.7.0 blur (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "projectHome": "/home/gistart/work",
    "ignoredNames": [
      "__pycache__"
    ],
    "packagesWithKeymapsDisabled": [
      "bracket-matcher"
    ],
    "disabledPackages": [
      "bracket-matcher"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.0
atom-jinja2, v0.5.0
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
autocomplete-python, v0.5.3
django-templates, v0.5.0
ex-mode, v0.7.0
minimap, v4.13.3
python-tools, v0.4.1
vim-mode, v0.60.0
vim-mode-visual-block, v0.2.13
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
Can you check if there are maybe two ex-mode lines open? I remember a similar bug happening where the line didn't close itself when it lost focus so you could have two lines.

In some themes, the lines themselves are nigh on invisible, so the best way to check this might be seeing if there is extra space below your command line.

**Comment by gistart** [comment]
No, it's not the case. And I have to add: after I commented 

# atom.commands.add(@editorElement, 'blur', @cancel.bind(this))

some of messages remain: on "replace symbol" command r<new char> and on search /<search>

**Comment by jfoster39** [comment]
Running Atom 1.2.4 on OSX Yosemite. Had same issue, enabling shadow dom in settings resolved for me.

**Comment by mdarby** [comment]
Getting this every single time I save in Atom 1.5.3 (current). Any help?

**Comment by jfoster39** [comment]
@mdarby Did you enable the 'Use Shadow DOM' checkbox under settings?

**Comment by mdarby** [comment]
I had just recently turned that option off. That was it.

Thanks so much :)

On Thu, Feb 25, 2016 at 11:20 AM, Tyler Foster <notifications@github.com>
wrote:

> @mdarby <https://github.com/mdarby> Did you enable the 'Use Shadow DOM'
> checkbox under settings?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lloeki/ex-mode/issues/58#issuecomment-188860867>.
>



-- 


Cheers!


*Matt Darby, M.S.*
Web: matt-darby.com
Twitter: @mattdarby
