### ISSUE TITLE
Failed to activate the ex-mode package (dependency issue?)

### ISSUE THREAD

**Issue by JuanchoVilla** [lloeki/ex-mode#64]
The package throws this error whenever I try using it, I tried fixing it and I think the problem is with the dependencies, I looked for all of them with no avail. I would be pretty rad if you could tell me how to fix it.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: linux 3.16.0-4-amd64
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.5.1

### Stack Trace

Failed to activate the ex-mode package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/juanchovilla/.atom/packages/ex-mode/lib/ex-state.coffee:1:46)
  at Object.<anonymous> (/home/juanchovilla/.atom/packages/ex-mode/lib/ex-state.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/juanchovilla/.atom/packages/ex-mode/lib/ex-mode.coffee:2:11)
  at Object.<anonymous> (/home/juanchovilla/.atom/packages/ex-mode/lib/ex-mode.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:236:14)
  at /usr/share/atom/resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:222:20)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -2:24.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:24.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:23.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:23.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:21.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:20.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:20.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:19.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:18.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:14.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 13x -0:08.2.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  6x -0:07.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:05.8.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:01.5.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.2.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:00.5.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ex-mode, v0.5.1
minimap, v4.10.0
monokai, v0.14.0
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by lloeki** [comment]
Sounds like an update gone wrong. Had such issues with Atom in general. Try moving away `~/.atom` then install only `vim-mode` and `ex-mode`.

**Comment by amslezak** [comment]
Just to update, I can personally confirm that simply quitting atom, uninstalling, then re-installing vim-mode & ex-mode worked for me.  Simple copy and paste for your convenience. 

```apm remove vim-mode; apm remove ex-mode;
apm install vim-mode; apm install ex-mode```

I started atom and I was good again.

**Comment by plbowers** [comment]
I find I get this whenever I mess around with the packages directories manually, for instance checking out ex-mode from git rather than using the atom package manager.

I solve it fairly easily by going into the package directory (`~/.atom/packages/ex-mode` in this case) and issuing the command `apm install`. That takes care of any dependencies that I lost in my moving things around...
