### ISSUE TITLE
Uncaught TypeError: Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by pfn** [lloeki/ex-mode#70]
[Enter steps to reproduce below:]

1. block of java code
2. go to opening brace of method, `ma`
3. `%`
4. `:'a,.d`

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'end' of undefined

```
At C:\Users\pfnguyen\.atom\packages\ex-mode\lib\ex-state.coffee:56

TypeError: Cannot read property 'end' of undefined
  at Command.parseAddr (C:\Users\pfnguyen\.atom\packages\ex-mode\lib\command.coffee:26:37)
  at Command.execute (C:\Users\pfnguyen\.atom\packages\ex-mode\lib\command.coffee:101:21)
  at ExState.processOpStack (C:\Users\pfnguyen\.atom\packages\ex-mode\lib\ex-state.coffee:50:17)
  at ExState.pushOperations (C:\Users\pfnguyen\.atom\packages\ex-mode\lib\ex-state.coffee:40:6)
  at ExViewModel.ViewModel.confirm (C:\Users\pfnguyen\.atom\packages\ex-mode\lib\view-model.coffee:13:14)
  at ExViewModel.module.exports.ExViewModel.confirm (C:\Users\pfnguyen\.atom\packages\ex-mode\lib\ex-view-model.coffee:35:5)
  at ExViewModel.confirm (C:\Users\pfnguyen\.atom\packages\ex-mode\lib\ex-view-model.coffee:1:1)
  at ex-command-mode-input.ExCommandModeInputElement.confirm (C:\Users\pfnguyen\.atom\packages\ex-mode\lib\ex-command-mode-input-element.coffee:46:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\pfnguyen\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\pfnguyen\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61

```

### Commands

```
     -0:52.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -0:52.8.0 blur (atom-text-editor.editor.mini.is-focused)
 24x -0:18.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:17.5.0 vim-mode:search (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:17.5.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:16.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:16.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:14 vim-mode:move-to-last-character-of-line (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:13.8.0 vim-mode:bracket-matching-motion (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:12.1.0 vim-mode:mark (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:12.1.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:11.8.0 vim-mode:bracket-matching-motion (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:11.4.0 ex-mode:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:11.4.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:10.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:04.3.0 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
ex-mode, v0.5.1
language-scala, v1.1.3
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by lloeki** [comment]
This is sufficient to reproduce on an empty file:

```
ma
:'a,.d
```
