### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

### ISSUE THREAD

**Issue by tgrosinger** [lloeki/ex-mode#72]
1. Closed a buffer which had been open for a while with `:q`
There were multiple panes open at the time and this pane had two tabs open.

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.2
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

```
At /home/tgrosinger/.atom/packages/ex-mode/lib/ex-state.coffee:56

TypeError: Cannot read property 'getScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:1354:34)
  at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/usr/share/atom/resources/app.asar/src/text-editor.js:2496:44)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)
  at /usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:94:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/cursor.js:66:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroyed (/usr/share/atom/resources/app.asar/src/marker.js:232:20)
  at /usr/share/atom/resources/app.asar/src/marker.js:37:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:256:20)
  at Marker.module.exports.Marker.destroy (/usr/share/atom/resources/app.asar/src/marker.js:43:25)
  at Selection.module.exports.Selection.destroy (/usr/share/atom/resources/app.asar/src/selection.js:62:26)
  at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app.asar/src/text-editor.js:267:19)
  at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:456:18)
  at Pane.module.exports.Pane.destroyActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:431:12)
  at Ex.quit (/home/tgrosinger/.atom/packages/ex-mode/lib/ex.coffee:62:36)
  at Ex.q (/home/tgrosinger/.atom/packages/ex-mode/lib/ex.coffee:64:10)
  at /home/tgrosinger/.atom/packages/ex-mode/lib/ex.coffee:1:1
  at Command.execute (/home/tgrosinger/.atom/packages/ex-mode/lib/command.coffee:153:7)
  at ExState.processOpStack (/home/tgrosinger/.atom/packages/ex-mode/lib/ex-state.coffee:50:17)
  at ExState.pushOperations (/home/tgrosinger/.atom/packages/ex-mode/lib/ex-state.coffee:40:6)
  at ExViewModel.ViewModel.confirm (/home/tgrosinger/.atom/packages/ex-mode/lib/view-model.coffee:13:14)
  at ExViewModel.module.exports.ExViewModel.confirm (/home/tgrosinger/.atom/packages/ex-mode/lib/ex-view-model.coffee:35:5)
  at ExViewModel.confirm (/home/tgrosinger/.atom/packages/ex-mode/lib/ex-view-model.coffee:1:1)
  at ex-command-mode-input.ExCommandModeInputElement.confirm (/home/tgrosinger/.atom/packages/ex-mode/lib/ex-command-mode-input-element.coffee:46:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  3x -0:22.6.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:21.9.0 vim-mode:move-to-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:21.5.0 vim-mode:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:21.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:20.7.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
 71x -0:19.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:12.2.0 vim-mode:move-to-start-of-file (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.8.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.8.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:07.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:04.9.0 pane:show-next-item (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.8.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.8.0 ex-mode:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.7.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
ex-mode, v0.5.1
file-icons, v1.5.8
go-plus, v3.4.3
go-rename, v0.3.0
last-cursor-position, v0.9.0
vim-mode, v0.57.0
vim-surround, v0.7.2

# Dev
No dev packages
```

**Comment by lloeki** [comment]
I can't reproduce this the naive way. I don't use panes that much so there's little chance I'll stumble upon this.
