### ISSUE TITLE
Uncaught TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by jfchevrette** [lloeki/ex-mode#73]
[Enter steps to reproduce below:]

1. installed vim-mode and ex-mode
2. typed :e without any filename following it

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'charAt' of undefined

```
At /Users/jfchevrette/.atom/packages/ex-mode/lib/ex-state.coffee:56

TypeError: Cannot read property 'charAt' of undefined
  at Object.posix.isAbsolute (path.js:440:14)
  at getFullPath (/Users/jfchevrette/.atom/packages/ex-mode/lib/ex.coffee:34:27)
  at Ex.edit (/Users/jfchevrette/.atom/packages/ex-mode/lib/ex.coffee:102:20)
  at Ex.e (/Users/jfchevrette/.atom/packages/ex-mode/lib/ex.coffee:105:19)
  at /Users/jfchevrette/.atom/packages/ex-mode/lib/ex.coffee:1:1
  at Command.execute (/Users/jfchevrette/.atom/packages/ex-mode/lib/command.coffee:153:7)
  at ExState.processOpStack (/Users/jfchevrette/.atom/packages/ex-mode/lib/ex-state.coffee:50:17)
  at ExState.pushOperations (/Users/jfchevrette/.atom/packages/ex-mode/lib/ex-state.coffee:40:6)
  at ExViewModel.ViewModel.confirm (/Users/jfchevrette/.atom/packages/ex-mode/lib/view-model.coffee:13:14)
  at ExViewModel.module.exports.ExViewModel.confirm (/Users/jfchevrette/.atom/packages/ex-mode/lib/ex-view-model.coffee:35:5)
  at ExViewModel.confirm (/Users/jfchevrette/.atom/packages/ex-mode/lib/ex-view-model.coffee:1:1)
  at ex-command-mode-input.ExCommandModeInputElement.confirm (/Users/jfchevrette/.atom/packages/ex-mode/lib/ex-command-mode-input-element.coffee:46:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:12.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:11.6.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:10.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 10x -0:10.3.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:08.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:07.9.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:07.4.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:06.2.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:06.2.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:05.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:05.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 ex-mode:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.5.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:03.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "projectHome": "/Users/jfchevrette/code"
  }
}
```

### Installed Packages

```coffee
# User
ex-mode, v0.5.1
file-icons, v1.5.8
fonts, v0.5.0
language-terraform, v0.4.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by mleeds95** [comment]
See if e33dc15392ca5eeecaf72b3cefad031d08c3d258 fixes this. By the way I think one of the steps to reproduce should be to open a new file; this doesn't happen with files that already exist.

**Comment by lloeki** [comment]
Fixed in 84c548, preventing all forms of silent unsaved buffer replacement (includes this bug, along with the one mentioned by @romgrk in #48).
